apiVersion: v1
kind: Service
metadata:
  name: d-service
  namespace: smallest-edge-node-first
  annotations:
    prometheus.io/port: "service-port"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/part-of: dms
spec:
  selector:
    app: D-app
  type: NodePort
  ports:
    - name: service-port
      protocol: TCP
      port: 80
      nodePort: 30003
      targetPort: "go-app-port"
