# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-deployment
  namespace: smallest-edge-node-first
  labels:
    app: D-app
spec:
  selector:
    matchLabels:
      app: D-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: D-app
    spec:
      containers:
        - image: noisyboy9/scheduler_load_test
          imagePullPolicy: Always
          name: scheduler-load-test
          ports:
            - containerPort: 8080
              name: go-app-port
          resources:
            limits:
              cpu: 3000m
              memory: 2850Mi
            requests:
              cpu: 3000m
              memory: 2850Mi
      restartPolicy: Always
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - edge
