apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-general-config
  namespace: smallest-edge-node-first
data:
  config.yaml: |-
    app:
      env: "dev"

    logging:
      stdout: true
      level: "debug"

    scheduler:
      name: smallest-edge-node-first 
      namespace: smallest-edge-node-first
      algorithm: "smallest-fitting-edge-node-first"
      informerSyncPeriod: "15s"

    connector:
      mode: "in-cluster"
      masterURL: "172.20.2.4"
      kubeConfigPath: ""
