apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-general-config
  namespace: smallest-edge-node-first
data:
  config.yaml: |-
    app:
      env: "dev"

    logging:
      stdout: true
      level: "debug"

    scheduler:
      name: smallest-fitting-edge-node
      namespace: smallest-edge-node-first
      algorithm: "smallest-fitting-edge-node"
      informerSyncPeriod: "15s"
      edgeAnnotationKey: "momtaz/cluster-type"
      edgeAnnotationValue: "edge"


    connector:
      mode: "in-cluster"
      masterURL: "172.20.2.4"
      kubeConfigPath: ""
