apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-general-config
  namespace: smallest-edge-node-first
data:
  config.yaml: |-
    app:
      env: "dev"

    logging:
      stdout: true
      level: "debug"

    scheduler: 
      name: custom-scheduler 
      namespace: smallest-edge-node-first
      algorithm: smallest-fitting-edge-node 
