# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-deployment
  namespace: random-scheduler
  labels:
    app: A-app
spec:
  selector:
    matchLabels:
      app: A-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: A-app
    spec:
      containers:
        - image: noisyboy9/scheduler_load_test
          imagePullPolicy: Always
          name: scheduler-load-test
          ports:
            - containerPort: 8080
              name: go-app-port
          resources:
            limits:
              cpu: 1000m
              memory: 950Mi
            requests:
              cpu: 1000m
              memory: 950Mi
      restartPolicy: Always
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - edge
