apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-general-config
  namespace: random-scheduler
data:
  config.yaml: |-
    app:
      env: "dev"

    logging:
      stdout: true
      level: "debug"

    scheduler:
      name: random-scheduler
      namespace: random-scheduler
      algorithm: "random"
      informerSyncPeriod: "15s"
      edgeAnnotationKey: "momtaz/cluster-type"
      edgeAnnotationValue: "edge"
    
    
    connector:
      mode: "in-cluster"
      masterURL: "172.20.2.4"
      kubeConfigPath: ""
