apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-general-config
  namespace: custom-scheduler
data:
  config.yaml: |-
    app:
      env: "dev"

    logging:
      stdout: true
      level: "debug"

    scheduler: 
      name: custom-scheduler 
      namespace: custom-scheduler
      algorithm: random
