apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-general-config
  namespace: biggest-fitting-edge-node
data:
  config.yaml: |-
    app:
      env: "dev"

    logging:
      stdout: true
      level: "debug"

    scheduler:
      name: biggest-fitting-edge-node 
      namespace: biggest-fitting-edge-node
      algorithm: "random"
      informerSyncPeriod: "15s"

    connector:
      mode: "in-cluster"
      masterURL: "172.20.2.4"
      kubeConfigPath: ""
