kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: c-hpa
  namespace: cloud-first-scheduler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: c-deployment
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: scheduler_load_test_requests_per_second
        target:
          type: Value
          averageValue: 5
