apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-general-config
  namespace: cloud-first-scheduler-namespace
data:
  config.yaml: |-
    app:
      env: "dev"

    logging:
      stdout: true
      level: "debug"

    scheduler: 
      name: custom-scheduler 
      namespace: cloud-first-scheduler-namespace
      algorithm: cloud-first 
